
name: FreeBSD

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/freebsd.yml'
      - '.github/workflows/testrun.yml'



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testsshfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["13.2", "13.3", "13.4", "13.5", "14.0", "14.1", "14.2", "14.3", "15.0"]
        arch: ["aarch64", ""]
        runs: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        exclude:
          - release: 12.4
            arch: aarch64
          - release: 13.2
            arch: aarch64
          - release: 14.0
            arch: aarch64
          - runs: ubuntu-24.04-arm
            arch: ""


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: freebsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "sshfs"


  testnfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["12.4", "13.2", "13.3", "13.4", "13.5", "14.0", "14.1", "14.2", "14.3", "15.0"]
        arch: ["aarch64", ""]
        runs: ["ubuntu-24.04"]
        exclude:
          - release: 12.4
            arch: aarch64
          - release: 13.2
            arch: aarch64
          - release: 14.0
            arch: aarch64

    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: freebsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: nfs
   
  testscp-riscv64:
    strategy:
      fail-fast: false
      matrix:
        release: ["13.4", "13.5", "14.2", "14.3", "15.0"]
        arch: ["riscv64"]
        runs: ["ubuntu-24.04"]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: freebsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: scp