
name: OmniOS

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/omnios.yml'
      - '.github/workflows/testrun.yml'



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["r151046", "r151048", "r151050", "r151052", "r151054", "r151056"]
        arch: [""]
        runs: ["ubuntu-24.04"]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: omnios
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "nfs"



   
