
name: OpenIndiana

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/openindiana.yml'
      - '.github/workflows/testrun.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testsshfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["202510"]
        arch: [""]
        runs: ["ubuntu-24.04"]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: openindiana
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "sshfs"

  nfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["202510"]
        arch: [""]
        runs: ["ubuntu-24.04"]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: openindiana
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "nfs"



   
