
name: OpenBSD

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/openbsd.yml'
      - '.github/workflows/testrun.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testsshfs-old:
    strategy:
      fail-fast: false
      matrix:
        release: ["7.3", "7.4", "7.5", "7.6"]
        arch: ["aarch64", ""]
        runs: ["ubuntu-24.04"]
        exclude:
          - release: 7.3
            arch: aarch64


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: openbsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "sshfs"


  testnfs-old:
    strategy:
      fail-fast: false
      matrix:
        release: ["7.3", "7.4", "7.5", "7.6"]
        arch: ["aarch64", ""]
        runs: ["ubuntu-24.04"]
        exclude:
          - release: 7.3
            arch: aarch64

    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: openbsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "nfs"


  testsshfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["7.7", "7.8"]
        arch: ["aarch64", ""]
        runs: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        exclude:
          - runs: ubuntu-24.04-arm
            arch: ""

    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: openbsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "sshfs"

  testnfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["7.7", "7.8"]
        arch: ["aarch64", ""]
        runs: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        exclude:
          - runs: ubuntu-24.04-arm
            arch: ""

    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: openbsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "nfs"


  testscp-riscv64:
    strategy:
      fail-fast: false
      matrix:
        release: ["7.7", "7.8"]
        arch: ["riscv64"]
        runs: ["ubuntu-24.04"]

    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: openbsd
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: "scp"