
name: Solaris

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/solaris.yml'
      - '.github/workflows/testrun.yml'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["11.4", "11.4-gcc"]
        arch: [""]
        runs: ["ubuntu-24.04"]
        sync: ["nfs", "scp"]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: solaris
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}
      sync: ${{ matrix.sync }}



   
