
name: Windows

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.py'
      - '.github/workflows/testwindows.yml'
      - '.github/workflows/testrun.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testwindows:
    strategy:
      fail-fast: false
      matrix:
        os: ["freebsd", "netbsd", "openbsd", "solaris", "dragonflybsd", "omnios", "openindiana"]
        arch: [""]
        runs: ["windows-latest"]
        sync: ["scp"]
        exclude:
          - os: solaris
            arch: aarch64
          - os: dragonflybsd
            arch: aarch64
          - os: omnios
            arch: aarch64
          - os: openindiana
            arch: aarch64

    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      sync: ${{ matrix.sync }}



  testwindowsArm:
    strategy:
      fail-fast: false
      matrix:
        os: ["freebsd", "netbsd", "openbsd"]
        arch: [""]
        runs: ["windows-11-arm"]
        sync: ["scp"]


    uses: ./.github/workflows/testrun.yml
    secrets: inherit
    with:
      runs: ${{ matrix.runs }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      sync: ${{ matrix.sync }} 
      
      
      
